version: "3.7"

services:

    nginx:
        image: "nginx:latest"
        container_name: "nginx"
        volumes:
            - "./nginx_config:/etc/nginx/conf.d"
        restart: "always"
        ports:
            - "80:80"
            - "443:443"

        network_mode: host
